### ISSUE TITLE
Test with older versions of node.js

### ISSUE THREAD

**Issue by lifthrasiir** [lifthrasiir/roadroller#6]
Maybe I can use nvm or similar to test locally, or set up the CI instance to make sure that.

**Comment by CodyJasonBennett** [comment]
I think the native GitHub actions should do, although it's a matter of configuring how/what to test.

For example:

```yml
# .github/workflows/CI.yml
name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:  
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install
      - run: npm run build
      - run: npm run test
        env:
          CI: true
```
